// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClLO8tnpsGOjW3wvbtZ4P5bxTQox_8VD8',
    appId: '1:1092143676638:web:3bc08642d5c4a01e71d64f',
    messagingSenderId: '1092143676638',
    projectId: 'medical-app-c1b57',
    authDomain: 'medical-app-c1b57.firebaseapp.com',
    storageBucket: 'medical-app-c1b57.appspot.com',
    measurementId: 'G-DE1JVHZFY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZpeZJt24g4fxrjWg-hTDMZsF0TrT-yA',
    appId: '1:1092143676638:android:d469853b40c0a82b71d64f',
    messagingSenderId: '1092143676638',
    projectId: 'medical-app-c1b57',
    storageBucket: 'medical-app-c1b57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhzshpJcxgxZ6liL5D0c1XYiJyFdGfzo4',
    appId: '1:1092143676638:ios:95785ef404bd2e7071d64f',
    messagingSenderId: '1092143676638',
    projectId: 'medical-app-c1b57',
    storageBucket: 'medical-app-c1b57.appspot.com',
    iosBundleId: 'com.example.quickmedical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhzshpJcxgxZ6liL5D0c1XYiJyFdGfzo4',
    appId: '1:1092143676638:ios:95785ef404bd2e7071d64f',
    messagingSenderId: '1092143676638',
    projectId: 'medical-app-c1b57',
    storageBucket: 'medical-app-c1b57.appspot.com',
    iosBundleId: 'com.example.quickmedical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClLO8tnpsGOjW3wvbtZ4P5bxTQox_8VD8',
    appId: '1:1092143676638:web:edbbbf37ea63c33871d64f',
    messagingSenderId: '1092143676638',
    projectId: 'medical-app-c1b57',
    authDomain: 'medical-app-c1b57.firebaseapp.com',
    storageBucket: 'medical-app-c1b57.appspot.com',
    measurementId: 'G-VK257DRRM0',
  );
}
